ERROR 2022-03-29 16:04:46,016 retry_on_timeout 96082 140291560376128 create_client() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
TypeError: create_client() missing 1 required positional argument: 'self'
ERROR 2022-03-29 16:04:58,821 retry_on_timeout 96101 140444217698112 create_client() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
TypeError: create_client() missing 1 required positional argument: 'self'
ERROR 2022-03-29 16:05:21,385 retry_on_timeout 96142 140415089837888 create_client() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
TypeError: create_client() missing 1 required positional argument: 'self'
