ERROR 2022-02-18 21:06:20,091 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:06:21,102 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:06:22,107 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:06:23,114 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:06:24,120 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:06:25,126 bot_handler 25803 139677421512448 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:07:47,574 bot_handler 25854 139648025745152 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:08:41,799 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:08:42,808 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:08:43,815 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:08:44,820 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:08:45,827 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:08:46,833 bot_handler 25929 140416170153728 Event loop is closed
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 193, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 238, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 269, in close_ws
    asyncio.ensure_future(client.close(), loop=loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 429, in create_task
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR 2022-02-18 21:09:04,723 bot_handler 25967 140540666590976 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:09:13,737 bot_handler 25967 140540666590976 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:09:19,746 bot_handler 25967 140540666590976 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:13:42,936 bot_handler 26185 140132871444224 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:13:49,946 bot_handler 26185 140132871444224 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:16:14,872 bot_handler 26398 140574740965120 Creating bot failed because position with symbol BTC/USDT is duplicate!
ERROR 2022-02-18 21:16:20,906 bot_handler 26398 140574740965120 Creating bot failed because position with symbol BTC/USDT is duplicate!
