ERROR 2022-08-08 21:56:39,019 bot_handler 181911 139647380342528 list index out of range
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 255, in run_bots_semi_limit_order_based
    bot.execute_operations2(operations)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 162, in execute_operations2
    precision = find_decimal_place(contract['tickSize'])
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/math.py", line 11, in find_decimal_place
    return len(str(n).split(".")[1])
IndexError: list index out of range
ERROR 2022-08-08 21:56:59,908 bot_handler 181911 139647947917120 Creating bot failed because position with symbol VET/USDT is duplicate!
ERROR 2022-08-08 21:57:37,335 bot_handler 182587 139866812479232 list index out of range
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 255, in run_bots_semi_limit_order_based
    bot.execute_operations2(operations)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 153, in execute_operations2
    def execute_operations2(self,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/math.py", line 10, in find_decimal_place
    def find_decimal_place(n):
IndexError: list index out of range
ERROR 2022-08-08 21:58:10,881 bot_handler 182692 140383956494080 list index out of range
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 266, in run_bots_semi_limit_order_based
    time.sleep(1)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 153, in execute_operations2
    def execute_operations2(self,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/math.py", line 10, in find_decimal_place
    def find_decimal_place(n):
IndexError: list index out of range
